using System.Xml.Linq;
using Xunit;

namespace DictaMeeting.Tests;

public class GenerateResourcesHelper
{
    // Este test genera y sincroniza Strings.resx, Strings.es.resx y Strings.en.resx
    // asegurando consistencia 100% y escape XML perfecto.
    [Fact(Skip = "Herramienta de desarrollo: ejecutar manualmente cuando se modifique el diccionario de recursos.")]
    public void GenerateAndVerifyResourceFiles()
    {
        var dict = new Dictionary<string, (string es, string en)>
        {
            // App & Header
            ["App_Title"] = ("DictaMeeting", "DictaMeeting"),
            ["App_Subtitle"] = ("Transcriptor de Reuniones", "Meeting Transcriber"),
            ["App_ByAuthor"] = ("byAritz", "byAritz"),
            ["App_Tagline"] = ("Transcripción local y privada de reuniones para Windows.", "Local and private meeting transcription for Windows."),
            ["App_Status_Ready"] = ("Listo para grabar", "Ready to record"),
            ["App_Status_Recording"] = ("Grabando reunión...", "Recording meeting..."),
            ["App_Status_Paused"] = ("Grabación en pausa", "Recording paused"),
            ["App_Status_Processing"] = ("Procesando transcripción y acta...", "Processing transcript and minutes..."),
            ["App_Audio_Monitor_Tooltip"] = ("Activar vúmetros para comprobar entrada de audio", "Enable level meters to check audio input"),
            ["App_Developed_By"] = ("Desarrollado por ", "Developed by "),
            ["App_Local_Badge"] = ("🔒 100% Local", "🔒 100% Local"),

            // Navigation & Tabs
            ["Nav_Meeting"] = ("Reunión", "Meeting"),
            ["Nav_History"] = ("Historial", "History"),
            ["Nav_NewMeeting"] = ("Nueva Reunión", "New Meeting"),
            ["Nav_NewMeeting_Tooltip"] = ("Iniciar una nueva reunión o importar archivo de audio", "Start a new meeting or import an audio file"),
            ["Nav_ImportAudio"] = ("Importar audio", "Import audio"),
            ["Nav_ImportTranscript"] = ("Importar transcripción", "Import transcript"),
            ["Nav_Settings"] = ("Ajustes", "Settings"),
            ["Nav_Settings_Tooltip"] = ("Ajustes", "Settings"),

            // Central Strip & Recording Controls
            ["Meeting_Title_Default"] = ("Nueva Reunión", "New Meeting"),
            ["Meeting_Title_Placeholder"] = ("Título de la reunión...", "Meeting title..."),
            ["Meeting_Title_Edit_Tooltip"] = ("Haz clic o pulsa el lápiz para editar el título", "Click or press pencil to edit title"),
            ["Meeting_Title_Save_Tooltip"] = ("Guardar título", "Save title"),
            ["Meeting_Folder_Tooltip"] = ("Abrir carpeta de la reunión", "Open meeting folder"),
            ["Meeting_Start"] = ("Iniciar", "Start"),
            ["Meeting_Starting"] = ("Iniciando...", "Starting..."),
            ["Meeting_Start_Full"] = ("Iniciar Reunión", "Start Meeting"),
            ["Meeting_Start_Tooltip"] = ("Comenzar grabación y transcripción de la reunión", "Start recording and meeting transcription"),
            ["Meeting_Starting_Tooltip"] = ("Inicializando modelos de voz y captura de audio...", "Initializing voice models and audio capture..."),
            ["Meeting_Pause"] = ("Pausar", "Pause"),
            ["Meeting_Pause_Tooltip"] = ("Pausar la grabación temporalmente", "Temporarily pause recording"),
            ["Meeting_Resume"] = ("Reanudar", "Resume"),
            ["Meeting_Resume_Tooltip"] = ("Continuar con la grabación", "Resume recording"),
            ["Meeting_Stop"] = ("Detener", "Stop"),
            ["Meeting_Stopping"] = ("Deteniendo...", "Stopping..."),
            ["Meeting_Stop_Full"] = ("Detener y Procesar", "Stop & Process"),
            ["Meeting_Stop_Tooltip"] = ("Detener grabación y procesar reunión", "Stop recording and process meeting"),
            ["Meeting_Stopping_Tooltip"] = ("Finalizando tareas en segundo plano y deteniendo grabación...", "Finishing background tasks and stopping recording..."),
            ["Meeting_Prepared"] = ("Preparado", "Ready"),
            ["Meeting_Ready_Subtitle"] = ("Listo para iniciar la grabación", "Ready to start recording"),
            ["Meeting_Starting_Subtitle"] = ("Cargando motor de voz y dispositivos...", "Loading voice engine and devices..."),
            ["Meeting_Cancel"] = ("Cancelar", "Cancel"),
            ["Meeting_Mic_Muted_Alert"] = ("Tu micrófono está silenciado", "Your microphone is muted"),
            ["Meeting_Mic_Muted_Detail"] = ("Se ha detectado sonido en tu sala, pero tu voz no se está grabando mientras el micrófono esté silenciado.", "Sound has been detected in your room, but your voice is not being recorded while the microphone is muted."),
            ["Meeting_Unmute_Button"] = ("Reactivar micrófono (Ctrl+M)", "Unmute microphone (Ctrl+M)"),
            ["Meeting_Language_Auto"] = ("Auto (Español + Inglés)", "Auto (Spanish + English)"),
            ["Meeting_Language_Spanish"] = ("Español", "Español"),
            ["Meeting_Language_English"] = ("English", "English"),
            ["Meeting_Language_Tooltip"] = ("Idioma principal de la reunión", "Main meeting language"),
            ["Meeting_Completed_Badge"] = ("Reunión Completada", "Meeting Completed"),
            ["Meeting_Reprocess_Button"] = ("Reprocesar Audio", "Reprocess Audio"),
            ["Meeting_Reprocess_Tooltip"] = ("Volver a procesar el audio grabado con otro modelo de transcripción", "Reprocess recorded audio with another transcription model"),
            ["Meeting_In_Progress_Alert"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de iniciar una nueva sesión.", "A meeting is actively recording or initializing. Please wait or stop it before starting a new session."),
            ["Meeting_In_Progress_Title"] = ("Reunión en Curso", "Meeting in Progress"),
            ["Meeting_Import_Audio_In_Progress"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de importar audio.", "A meeting is actively recording or initializing. Please wait or stop it before importing audio."),
            ["Meeting_Import_Transcript_In_Progress"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de importar una transcripción.", "A meeting is actively recording or initializing. Please wait or stop it before importing a transcript."),
            ["Meeting_Duration_Label"] = ("Duración: {0}", "Duration: {0}"),
            ["Meeting_Audio_Available"] = ("Audio grabado disponible", "Recorded audio available"),
            ["Meeting_Audio_Processing"] = ("Procesando audio...", "Processing audio..."),
            ["Meeting_Audio_None"] = ("Sin archivo de audio", "No audio file"),
            ["Meeting_Status_Completed"] = ("Completada", "Completed"),
            ["Meeting_Status_Prepared"] = ("Preparada", "Ready"),
            ["Meeting_Status_Recording"] = ("Grabando", "Recording"),
            ["Meeting_Models_Summary"] = ("En vivo ({0}) / Procesado ({1})", "Live ({0}) / Processed ({1})"),
            ["Meeting_Audio_Sources_Tooltip"] = ("{0} • {1}", "{0} • {1}"),
            ["Meeting_Participant_Single"] = ("1 participante", "1 participant"),
            ["Meeting_Participant_Multiple"] = ("{0} participantes", "{0} participants"),
            ["Meeting_Header_Models_Tooltip"] = ("Modelos configurados para transcripción en vivo y definitiva", "Models configured for live and final transcription"),
            ["Meeting_Header_Language_Tooltip"] = ("Idioma de reconocimiento", "Recognition language"),
            ["Meeting_Header_Participants_Tooltip"] = ("Número de participantes registrados o detectados", "Number of registered or detected participants"),
            ["AudioSource_MicSys"] = ("Micrófono · Sistema", "Microphone · System"),
            ["AudioSource_Mic"] = ("Micrófono", "Microphone"),
            ["AudioSource_Sys"] = ("Audio del sistema", "System audio"),
            ["AudioSource_None"] = ("Sin audio", "No audio"),
            ["AudioSource_Mic_Enabled"] = ("Micrófono: {0}", "Microphone: {0}"),
            ["AudioSource_Mic_Disabled"] = ("Micrófono: Desactivado", "Microphone: Disabled"),
            ["AudioSource_Sys_Enabled"] = ("Sistema: {0}", "System: {0}"),
            ["AudioSource_Sys_Disabled"] = ("Sistema: Desactivado", "System: Disabled"),
            ["AudioSource_Activated"] = ("Activado", "Enabled"),
            ["AudioSettings_MicLevel_Tooltip"] = ("Nivel de entrada del micrófono", "Microphone input level"),
            ["AudioSettings_SystemLevel_Tooltip"] = ("Nivel de audio del sistema (WASAPI Loopback)", "System audio level (WASAPI Loopback)"),
            ["History_Quick_New"] = ("+ Crear Nueva Reunión", "+ Create New Meeting"),
            ["History_Intervention_Single"] = ("1 intervención", "1 intervention"),
            ["History_Interventions_Multiple"] = ("{0} intervenciones", "{0} interventions"),
            ["History_Default_Speaker"] = ("Locutor", "Speaker"),
            ["Models_Button_Settings"] = ("Ajustes", "Settings"),

            // Audio Mute/Unmute & Player
            ["Audio_Mic_Label"] = ("Micrófono", "Microphone"),
            ["Audio_Mic_Muted_Label"] = ("Mic (Silenciado)", "Mic (Muted)"),
            ["Audio_Mic_Mute_Tooltip"] = ("Silenciar micrófono temporalmente (Ctrl+M)", "Temporarily mute microphone (Ctrl+M)"),
            ["Audio_Mic_Unmute_Tooltip"] = ("Micrófono silenciado. Clic o Ctrl+M para reactivar", "Microphone muted. Click or Ctrl+M to unmute"),
            ["Audio_System_Label"] = ("Audio del sistema", "System audio"),
            ["Audio_System_Muted_Label"] = ("Sistema (Silenciado)", "System (Muted)"),
            ["Audio_System_Mute_Tooltip"] = ("Silenciar audio del sistema temporalmente", "Temporarily mute system audio"),
            ["Audio_System_Unmute_Tooltip"] = ("Audio del sistema silenciado. Clic para reactivar", "System audio muted. Click to unmute"),
            ["Audio_Player_Play_Tooltip"] = ("Reproducir audio (Espacio)", "Play audio (Space)"),
            ["Audio_Player_Pause_Tooltip"] = ("Pausar audio (Espacio)", "Pause audio (Space)"),
            ["Audio_Player_Volume_Muted_Tooltip"] = ("Audio silenciado (clic para activar)", "Audio muted (click to unmute)"),
            ["Audio_Player_Volume_Tooltip"] = ("Volumen: {0} (clic para silenciar)", "Volume: {0} (click to mute)"),

            // Dynamic Header Titles
            ["Transcript_Header_Processing"] = ("TRANSCRIPCIÓN · PROCESANDO", "TRANSCRIPTION · PROCESSING"),
            ["Transcript_Header_Live"] = ("TRANSCRIPCIÓN EN VIVO", "LIVE TRANSCRIPTION"),
            ["Transcript_Header_Final"] = ("TRANSCRIPCIÓN FINAL", "FINAL TRANSCRIPT"),
            ["Transcript_Header_Default"] = ("TRANSCRIPCIÓN", "TRANSCRIPTION"),
            ["Transcript_Subtitle_Processing"] = ("• Procesando modelo de alta fidelidad...", "• Processing high-fidelity model..."),
            ["Transcript_Subtitle_Completed"] = ("• Alta fidelidad (Transcripción + Diarización)", "• High-fidelity (Transcription + Diarization)"),
            ["Transcript_Subtitle_Live"] = ("• Flujo continuo en vivo", "• Live continuous stream"),
            ["Transcript_Subtitle_Default"] = ("• Flujo continuo", "• Continuous stream"),
            ["Summary_Header_Processing"] = ("RESUMEN", "SUMMARY"),
            ["Summary_Header_Live"] = ("RESUMEN EN VIVO", "LIVE SUMMARY"),
            ["Summary_Header_Final"] = ("RESUMEN FINAL", "FINAL SUMMARY"),

            // Workspace Left Panel: Live Transcription
            ["Live_Title"] = ("Transcripción en vivo", "Live transcription"),
            ["Live_Waiting"] = ("A la espera de transcripción...", "Waiting for transcription..."),
            ["Live_Interventions_Empty"] = ("No hay intervenciones transcritas en esta reunión.", "No transcribed interventions in this meeting."),
            ["Live_Copy_Tooltip"] = ("Copiar transcripción al portapapeles", "Copy transcript to clipboard"),
            ["Live_Export_Tooltip"] = ("Exportar transcripción en formato Markdown, Texto plano o JSON", "Export transcript as Markdown, Plain text or JSON"),
            ["Live_Badge_Local"] = ("100% Local", "100% Local"),

            // Workspace Right Panel: Summary & Minutes
            ["Summary_Tab"] = ("Resumen", "Summary"),
            ["Minutes_Tab"] = ("Acta", "Minutes"),
            ["Summary_Title"] = ("Resumen en Vivo con IA", "Live AI Summary"),
            ["Summary_Description"] = ("Cada 1 o 2 minutos se generará automáticamente una tarjeta con el resumen del tramo (~50 palabras).", "Every 1 or 2 minutes a summary card of the segment (~50 words) will be automatically generated."),
            ["Summary_Card_JustNow"] = ("Hace un instante", "Just now"),
            ["Summary_Card_SecondsAgo"] = ("Hace {0} s", "{0}s ago"),
            ["Summary_Card_OneMinuteAgo"] = ("Hace 1 min", "1 min ago"),
            ["Summary_Card_MinutesAgo"] = ("Hace {0} min", "{0} mins ago"),
            ["Minutes_Title"] = ("Acta Ejecutiva con IA", "Executive AI Minutes"),
            ["Minutes_Description"] = ("Genera un resumen formal y estructurado con acuerdos, decisiones y tareas de esta reunión utilizando inteligencia artificial.", "Generate a formal, structured summary with agreements, decisions and action items from this meeting using artificial intelligence."),
            ["Minutes_Generate_Button"] = ("Redactar Acta con IA", "Draft Minutes with AI"),
            ["Minutes_Generate_Button_Short"] = ("Generar Acta", "Generate Minutes"),
            ["Minutes_Generate_Tooltip"] = ("Generar acta ejecutiva de la reunión con IA", "Generate executive meeting minutes with AI"),
            ["Minutes_Regenerate_Button"] = ("Redactar de nuevo", "Redraft"),
            ["Minutes_Regenerate_Tooltip"] = ("Volver a redactar o personalizar el acta con IA", "Redraft or customize minutes with AI"),
            ["Minutes_Copy_Tooltip"] = ("Copiar acta al portapapeles", "Copy minutes to clipboard"),
            ["Minutes_Save_Md"] = ("Guardar .md", "Save .md"),
            ["Minutes_Save_Md_Tooltip"] = ("Guardar acta en archivo Markdown (.md)", "Save minutes to Markdown file (.md)"),
            ["Minutes_Impersonal_Option"] = ("Acta impersonal", "Impersonal minutes"),
            ["Minutes_Impersonal_Tooltip"] = ("Redacta el acta de forma impersonal sin atribuir intervenciones ni incluir códigos SPEAKER_XX", "Draft minutes impersonally without attributing interventions or including SPEAKER_XX codes"),
            ["Minutes_Format_Markdown"] = ("Markdown (.md)", "Markdown (.md)"),
            ["Minutes_Format_Text"] = ("Texto Plano (.txt)", "Plain Text (.txt)"),
            ["Minutes_Format_Json"] = ("Archivo JSON (.json)", "JSON File (.json)"),

            // Participants Panel
            ["Participants_Title"] = ("PARTICIPANTES", "PARTICIPANTS"),
            ["Participants_Add_Button"] = ("+ Añadir", "+ Add"),
            ["Participants_Add_Placeholder"] = ("Escribe el nombre del participante y presiona Enter o Añadir", "Enter participant name and press Enter or Add"),
            ["Participants_Empty"] = ("Añade los asistentes para asociarlos a las voces.", "Add attendees to associate them with voices."),
            ["Participants_Delete_Tooltip"] = ("Eliminar de la lista de participantes", "Remove from participants list"),
            ["Participants_Voices_Title"] = ("VOCES DETECTADAS", "DETECTED VOICES"),
            ["Participants_Voices_Subtitle"] = ("Selecciona en el desplegable quién es cada voz.", "Select from dropdown who belongs to each voice."),
            ["Participants_Voice_Select_Tooltip"] = ("Selecciona el asistente correspondiente a esta voz", "Select the attendee corresponding to this voice"),
            ["Participants_Speaking_Time_Tooltip"] = ("Tiempo total de habla", "Total speaking time"),
            ["Participants_Registered_Format"] = ("{0} registrados", "{0} registered"),
            ["Participants_Voices_Format"] = ("{0} voces", "{0} voices"),
            ["Participants_Interventions_Format"] = ("{0} interv.", "{0} interv."),

            // History
            ["History_Title"] = ("Historial de Reuniones", "Meeting History"),
            ["History_Subtitle"] = ("HISTORIAL GUARDADO", "SAVED HISTORY"),
            ["History_Search_Placeholder"] = ("Buscar por título, fecha o texto...", "Search by title, date or text..."),
            ["History_Empty"] = ("No hay reuniones guardadas", "No saved meetings found"),
            ["History_Select_Prompt"] = ("Selecciona una reunión del historial", "Select a meeting from history"),
            ["History_Select_Hint"] = ("Podrás examinar su información preliminar y pulsar 'Ver reunión' para abrirla en el espacio de trabajo principal.", "You can inspect preliminary details and click 'View meeting' to open it in the main workspace."),
            ["History_Open_Button"] = ("Ver reunión", "View meeting"),
            ["History_Open_Arrow_Button"] = ("Abrir reunión →", "Open meeting →"),
            ["History_Open_Tooltip"] = ("Cargar esta reunión completa en la pantalla de 'Reunión' para trabajar con ella", "Load this complete meeting into the 'Meeting' workspace to work with it"),
            ["History_Open_Workspace_Tooltip"] = ("Abrir esta reunión en el workspace principal de Reunión", "Open this meeting in the main Meeting workspace"),
            ["History_Delete_Button"] = ("Eliminar", "Delete"),
            ["History_Delete_Confirm"] = ("¿Estás seguro de que deseas eliminar esta reunión? Esta acción borrará la transcripción, el acta y los datos asociados.", "Are you sure you want to delete this meeting? This action will delete the transcript, minutes and associated data."),
            ["History_Preview_Transcript"] = ("VISTA PREVIA DE TRANSCRIPCIÓN", "TRANSCRIPT PREVIEW"),
            ["History_Preview_Summary"] = ("VISTA PREVIA DE RESUMEN", "SUMMARY PREVIEW"),
            ["History_Detail_Notice"] = ("Para ver la transcripción completa, editar o mapear locutores, redactar un acta o reprocesar el audio, abre esta reunión en detalle.", "To view the full transcript, edit or map speakers, draft minutes or reprocess audio, open this meeting in detail."),
            ["History_Pill_Transcript"] = ("✓ Transcripción", "✓ Transcript"),
            ["History_Pill_Summary"] = ("✓ Resumen", "✓ Summary"),
            ["History_Pill_Acta"] = ("⚡ Acta", "⚡ Minutes"),
            ["History_Total_Segments"] = ("{0} fragmentos totales", "{0} total segments"),
            ["History_Remaining_Segments"] = ("y {0} intervenciones más...", "and {0} more interventions..."),
            ["History_No_Summary"] = ("Esta reunión no dispone de resumen generado.", "This meeting does not have a generated summary."),
            ["History_Acta_Status_Done"] = ("✓ Acta ejecutiva redactada", "✓ Executive minutes drafted"),
            ["History_Acta_Status_None"] = ("— Sin acta redactada", "— No minutes drafted"),
            ["History_Status_Processing"] = ("Procesando {0}%", "Processing {0}%"),
            ["History_Status_Pending"] = ("Pendiente", "Pending"),
            ["History_Status_Cancelled"] = ("Cancelado", "Cancelled"),
            ["History_Status_Completed"] = ("Completado", "Completed"),
            ["History_Summary_Line"] = ("{0} participantes • {1} interv.", "{0} participants • {1} interv."),
            ["History_No_Participants"] = ("Sin participantes registrados", "No registered participants"),
            ["History_Detected_Voices_Format"] = ("{0} voces detectadas ({1})", "{0} detected voices ({1})"),

            // Audio Player
            ["Player_Play"] = ("Reproducir", "Play"),
            ["Player_Pause"] = ("Pausar", "Pause"),
            ["Player_Replay5"] = ("Retroceder 5 segundos", "Back 5 seconds"),
            ["Player_Forward5"] = ("Avanzar 5 segundos", "Forward 5 seconds"),
            ["Player_Speed"] = ("Velocidad", "Speed"),
            ["Player_Volume"] = ("Volumen", "Volume"),
            ["Player_Idle"] = ("Audio en reposo", "Audio idle"),

            // Settings
            ["Settings_Title"] = ("Ajustes", "Settings"),
            ["Settings_General_Title"] = ("Ajustes Generales", "General Settings"),
            ["Settings_Card_Models_Title"] = ("Modelos de transcripción", "Transcription models"),
            ["Settings_Card_Models_Subtitle"] = ("Gestiona los modelos de voz locales.", "Manage local voice models."),
            ["Settings_Card_Models_Tooltip"] = ("Gestionar y examinar modelos de transcripción local", "Manage and inspect local transcription models"),
            ["Settings_Card_Ai_Title"] = ("Proveedores de IA", "AI providers"),
            ["Settings_Card_Ai_Subtitle"] = ("Configura los servicios para generar actas.", "Configure services to generate minutes."),
            ["Settings_Card_Ai_Tooltip"] = ("Configurar clave API e integración de inteligencia artificial", "Configure API key and artificial intelligence integration"),
            ["Settings_Card_Vocab_Title"] = ("Vocabulario y palabras clave", "Vocabulary & keywords"),
            ["Settings_Card_Vocab_Subtitle"] = ("Mejora el reconocimiento de nombres y términos.", "Improve recognition of names and technical terms."),
            ["Settings_Card_Vocab_Tooltip"] = ("Gestionar glosario de términos, acrónimos y expresiones fonéticas", "Manage glossary of terms, acronyms and phonetic variants"),
            ["Settings_Card_Privacy_Title"] = ("Privacidad y grabación", "Privacy & recording"),
            ["Settings_Card_Privacy_Subtitle"] = ("Consulta cómo se procesan y almacenan tus datos.", "Check how your data is processed and stored."),
            ["Settings_Card_Privacy_Tooltip"] = ("Información sobre procesamiento local, avisos de grabación y privacidad", "Information on local processing, recording notices and privacy"),
            ["Settings_Card_Privacy_Badge"] = ("Local / Remoto", "Local / Remote"),
            ["Settings_Card_System_Title"] = ("Sistema", "System"),
            ["Settings_Card_System_Subtitle"] = ("Tema e idioma de la aplicación", "Application theme and language"),
            ["Settings_Card_System_Tooltip"] = ("Configurar el tema visual y el idioma de la interfaz", "Configure visual theme and interface language"),
            ["Settings_Card_About_Title"] = ("Acerca de", "About"),
            ["Settings_Card_About_Subtitle"] = ("Información sobre DictaMeeting, su autor y las tecnologías utilizadas.", "Information about DictaMeeting, author and technologies used."),
            ["Settings_Card_About_Tooltip"] = ("Información sobre DictaMeeting, su autor y tecnologías", "Information about DictaMeeting, author and technologies"),
            ["Settings_Theme_Light"] = ("Claro", "Light"),
            ["Settings_Theme_Dark"] = ("Oscuro", "Dark"),
            ["Theme_Toggle_Light_Tooltip"] = ("Modo claro (clic para cambiar a oscuro)", "Light mode (click to switch to dark)"),
            ["Theme_Toggle_Dark_Tooltip"] = ("Modo oscuro (clic para cambiar a claro)", "Dark mode (click to switch to light)"),

            // System Modal
            ["System_Modal_Title"] = ("Sistema", "System"),
            ["System_Modal_Subtitle"] = ("Tema e idioma de la aplicación", "Application theme and language"),
            ["System_Section_Theme_Title"] = ("TEMA", "THEME"),
            ["System_Section_Language_Title"] = ("IDIOMA", "LANGUAGE"),
            ["System_Theme_Light"] = ("Claro", "Light"),
            ["System_Theme_Dark"] = ("Oscuro", "Dark"),
            ["System_Language_Spanish"] = ("Español", "Español"),
            ["System_Language_English"] = ("English", "English"),
            ["System_Language_Hint"] = ("El idioma de la interfaz es independiente del idioma de transcripción de las reuniones.", "The interface language is independent of the meeting transcription language."),

            // Audio Devices & Model Settings Modal
            ["AudioSettings_Title"] = ("Ajustes de Grabación y Modelos", "Recording & Models Settings"),
            ["AudioSettings_InputDevices"] = ("Dispositivos de Entrada de Audio", "Audio Input Devices"),
            ["AudioSettings_Mic"] = ("Micrófono", "Microphone"),
            ["AudioSettings_Mic_Capture"] = ("Capturar micrófono", "Capture microphone"),
            ["AudioSettings_Mic_Tooltip"] = ("Dispositivo de micrófono a capturar", "Microphone device to capture"),
            ["AudioSettings_SystemAudio"] = ("Audio del sistema", "System audio"),
            ["AudioSettings_SystemAudio_Capture"] = ("Capturar audio del sistema", "Capture system audio"),
            ["AudioSettings_SystemAudio_Tooltip"] = ("Dispositivo de audio de salida para capturar participantes remotos", "Output audio device to capture remote participants"),
            ["AudioSettings_Refresh"] = ("Actualizar", "Refresh"),
            ["AudioSettings_Refresh_Tooltip"] = ("Escanear nuevamente dispositivos conectados o desconectados", "Scan connected or disconnected devices again"),
            ["AudioSettings_TestAudio"] = ("Probar Audio", "Test Audio"),
            ["AudioSettings_TestAudio_Stop"] = ("Detener Prueba", "Stop Test"),
            ["AudioSettings_TestAudio_Tooltip"] = ("Activa los vúmetros para comprobar la entrada de audio antes de iniciar la reunión", "Activate level meters to check audio input before starting meeting"),
            ["AudioSettings_ModelsAndLang"] = ("Modelos de transcripción e idioma", "Transcription models & language"),
            ["AudioSettings_LiveModel"] = ("Modelo en vivo", "Live model"),
            ["AudioSettings_LiveModel_Tooltip"] = ("Modelo ligero para transcripción en tiempo real", "Lightweight model for real-time transcription"),
            ["AudioSettings_FinalModel"] = ("Modelo final", "Final model"),
            ["AudioSettings_FinalModel_Tooltip"] = ("Modelo de alta fidelidad para consolidación final", "High-fidelity model for final consolidation"),
            ["AudioSettings_Language"] = ("Idioma predominante", "Predominant language"),
            ["AudioSettings_Language_Tooltip"] = ("Idioma de reconocimiento", "Recognition language"),
            ["AudioSettings_AutoSave_Note"] = ("Los ajustes se guardan automáticamente para futuras reuniones.", "Settings are automatically saved for future meetings."),

            // Models Manager Modal
            ["Models_Title"] = ("Modelos de transcripción", "Transcription models"),
            ["Models_Location_Title"] = ("Ubicación de los modelos", "Models location"),
            ["Models_Location_Desc"] = ("Los modelos pueden ocupar varios GB. Puedes almacenarlos en otra unidad.", "Models can take several GBs. You can store them on another drive."),
            ["Models_Change_Folder"] = ("Cambiar ubicación", "Change location"),
            ["Models_Restore_Default"] = ("Restablecer", "Reset default"),
            ["Models_Status_Downloaded"] = ("Descargado", "Downloaded"),
            ["Models_Status_Available"] = ("Disponible", "Available"),
            ["Models_Status_Downloading"] = ("Descargando...", "Downloading..."),
            ["Models_Status_Pending"] = ("Pendiente", "Pending"),
            ["Models_Action_Download"] = ("Descargar Modelo Local", "Download Local Model"),
            ["Models_Action_Cancel"] = ("Cancelar descarga", "Cancel download"),
            ["Models_Action_Retry"] = ("Reintentar descarga", "Retry download"),
            ["Models_Action_Delete"] = ("Eliminar", "Delete"),
            ["Models_Action_Delete_Tooltip"] = ("Eliminar archivo del modelo para liberar espacio", "Delete model file to free up space"),
            ["Models_Recommended_Badge"] = ("★ RECOMENDADO", "★ RECOMMENDED"),
            ["Models_Recommended_Subtitle"] = ("Recomendación Inteligente de Hardware", "Intelligent Hardware Recommendation"),
            ["Models_Recommended_Hardware"] = ("★ RECOMENDADO PARA TU EQUIPO", "★ RECOMMENDED FOR YOUR SYSTEM"),
            ["Models_Footer_Note"] = ("Los modelos se guardan localmente y funcionan 100% sin conexión a internet.", "Models are stored locally and work 100% offline."),
            ["Models_Default_Location"] = ("Ubicación predeterminada", "Default location"),
            ["Models_Custom_Location"] = ("Ubicación personalizada", "Custom location"),
            ["Models_Location_NotValid"] = ("La carpeta seleccionada no es válida.", "The selected folder is not valid."),
            ["Models_Location_Configured"] = ("La ubicación de los modelos se ha configurado en:\n{0}", "Models location configured to:\n{0}"),
            ["Models_Location_Title_Dialog"] = ("Ubicación de Modelos", "Models Location"),
            ["Models_Location_NotAvailable_Dialog"] = ("Ubicación No Disponible", "Location Not Available"),
            ["Models_Location_NotAvailable_Msg"] = ("La ubicación configurada ({0}) no está disponible. Conecte la unidad o seleccione otra ubicación antes de descargar.", "The configured location ({0}) is not available. Connect the drive or select another location before downloading."),
            ["Models_Delete_Confirm_Msg"] = ("¿Está seguro de que desea eliminar el archivo local del modelo '{0}' ({1}) para liberar espacio en disco?", "Are you sure you want to delete the local model file '{0}' ({1}) to free up disk space?"),
            ["Models_Delete_Confirm_Title"] = ("Eliminar Modelo Local", "Delete Local Model"),
            ["Models_Ready_Title"] = ("DictaMeeting — Modelo Listo", "DictaMeeting — Model Ready"),
            ["Models_Ready_Msg"] = ("El modelo {0} se ha descargado correctamente y está listo para transcribir.", "The model {0} has been downloaded successfully and is ready to transcribe."),
            ["Models_Download_Error_Title"] = ("Error de Descarga", "Download Error"),
            ["Models_Download_Error_Msg"] = ("Error al descargar el modelo {0}: {1}", "Error downloading model {0}: {1}"),
            ["Models_Download_Button_Format"] = ("⬇ Descargar ({0})", "⬇ Download ({0})"),

            // Model Migration Modal
            ["Migrate_Title"] = ("Mover modelos a la nueva ubicación", "Move models to new location"),
            ["Migrate_Subtitle"] = ("Se han encontrado modelos existentes en la ubicación actual.", "Existing models found in the current location."),
            ["Migrate_Current_Location"] = ("Ubicación actual (origen):", "Current location (source):"),
            ["Migrate_New_Location"] = ("Nueva ubicación (destino):", "New location (destination):"),
            ["Migrate_Total_Size"] = ("Tamaño total: {0}", "Total size: {0}"),
            ["Migrate_Models_Count"] = ("{0} modelos", "{0} models"),
            ["Migrate_Error_Title"] = ("⚠️ Error durante la migración", "⚠️ Error during migration"),
            ["Migrate_Move_Button"] = ("Mover modelos", "Move models"),
            ["Migrate_Keep_Button"] = ("Cambiar sin mover", "Change without moving"),
            ["Migrate_Keep_Tooltip"] = ("Los modelos existentes permanecerán en la carpeta anterior sin copiarse", "Existing models will remain in previous folder without copying"),
            ["Migrate_Cancel_Button"] = ("Cancelar migración", "Cancel migration"),
            ["Migrate_Warn_Msg"] = ("Los modelos existentes permanecerán en la ubicación anterior y no se copiarán a la nueva carpeta.\n\n¿Desea cambiar la ubicación de todos modos?", "Existing models will remain in the previous location and will not be copied to the new folder.\n\nDo you want to change location anyway?"),
            ["Migrate_Success_Msg"] = ("Todos los modelos han sido migrados con éxito y verificados en la nueva ubicación:\n{0}", "All models have been migrated successfully and verified in the new location:\n{0}"),
            ["Migrate_Success_Title"] = ("Migración Completada", "Migration Completed"),
            ["Migrate_Cancelled_Msg"] = ("La migración ha sido cancelada. Los modelos originales permanecen intactos en la ubicación anterior y no se ha modificado la configuración.", "Migration was cancelled. Original models remain intact in previous location and settings were not changed."),
            ["Migrate_Cancelled_Title"] = ("Migración Cancelada", "Migration Cancelled"),

            // AI Configuration Modal
            ["AiConfig_Title"] = ("Proveedores de IA", "AI Providers"),
            ["AiConfig_Subtitle"] = ("Conecta DictaMeeting a OpenRouter o a cualquier servidor compatible con la API de OpenAI, como LiteLLM.", "Connect DictaMeeting to OpenRouter or any OpenAI-compatible server such as LiteLLM."),
            ["AiConfig_Provider_Label"] = ("Proveedor de IA", "AI Provider"),
            ["AiConfig_Provider_OpenRouter"] = ("OpenRouter", "OpenRouter"),
            ["AiConfig_Provider_Custom"] = ("Servidor personalizado", "Custom server"),
            ["AiConfig_ApiKey_Label"] = ("API Key", "API Key"),
            ["AiConfig_ApiKey_Help"] = ("Clave de acceso al servicio (protegida con Windows DPAPI). Obtener en openrouter.ai/keys", "Service access key (protected with Windows DPAPI). Get at openrouter.ai/keys"),
            ["AiConfig_ApiKey_Placeholder"] = ("Clave de API de OpenRouter (sk-or-...)", "OpenRouter API key (sk-or-...)"),
            ["AiConfig_Model_Label"] = ("Modelo de IA", "AI Model"),
            ["AiConfig_Custom_Endpoint_Label"] = ("URL base del servidor.", "Server base URL."),
            ["AiConfig_Custom_Endpoint_Placeholder"] = ("URL base o endpoint del servidor (ej. https://mi-servidor.com/v1)", "Server base URL or endpoint (e.g. https://my-server.com/v1)"),
            ["AiConfig_Custom_Model_Label"] = ("Nombre del modelo disponible en el servidor.", "Model name available on the server."),
            ["AiConfig_Custom_Model_Placeholder"] = ("Nombre o identificador del modelo en su servidor (ej. qwen3.8-27b)", "Model name or identifier on your server (e.g. qwen3.8-27b)"),
            ["AiConfig_Test_Connection"] = ("Probar conexión", "Test connection"),
            ["AiConfig_Endpoint_Title"] = ("Endpoint", "Endpoint"),
            ["AiConfig_Model_Title"] = ("Modelo", "Model"),
            ["AiConfig_Save_Key_Button"] = ("💾 Guardar Clave", "💾 Save Key"),
            ["AiConfig_Delete_Button"] = ("🗑 Eliminar", "🗑 Delete"),
            ["AiConfig_Test_Button"] = ("⚡ Probar conexión", "⚡ Test connection"),
            ["AiConfig_Save_Config_Button"] = ("💾 Guardar Configuración", "💾 Save Settings"),
            ["AiConfig_Delete_Key_Button"] = ("🗑 Eliminar Clave", "🗑 Delete Key"),
            ["AiConfig_Custom_Key_Tooltip"] = ("Introduzca la clave de API del servidor personalizado", "Enter custom server API key"),
            ["AiConfig_Custom_Key_Help"] = ("Clave de acceso al servicio (protegida con Windows DPAPI).", "Service access key (protected with Windows DPAPI)."),
            ["AiConfig_OpenRouter_Key_Tooltip"] = ("Introduzca su clave de OpenRouter", "Enter your OpenRouter key"),
            ["AiConfig_Callout_Privacy"] = ("El contenido de la reunión se enviará al proveedor seleccionado al generar el acta.", "Meeting content will be sent to the selected provider when generating minutes."),
            ["AiConfig_Testing"] = ("Actualizando...", "Testing connection..."),
            ["AiConfig_Save_Key"] = ("Guardar Clave", "Save Key"),
            ["AiConfig_Save_Config"] = ("Guardar Configuración", "Save Settings"),
            ["AiConfig_Delete_Key"] = ("Eliminar Clave", "Delete Key"),
            ["AiConfig_Status_Connected"] = ("Conexión exitosa", "Connection successful"),
            ["AiConfig_Status_Failed"] = ("Error de conexión", "Connection failed"),
            ["AiConfig_Status_Configured"] = ("Configurado", "Configured"),
            ["AiConfig_Status_NotConfigured"] = ("No configurado", "Not configured"),
            ["AiConfig_KeySaved_DPAPI"] = ("✓ Clave guardada de forma segura con Windows DPAPI", "✓ Key stored securely with Windows DPAPI"),
            ["AiConfig_KeyNotConfigured_OpenRouter"] = ("⚠ Clave de OpenRouter no configurada", "⚠ OpenRouter API key not configured"),
            ["AiConfig_KeyNotConfigured_Custom"] = ("⚠ Clave de Servidor personalizado no configurada", "⚠ Custom server API key not configured"),
            ["AiConfig_OpenRouter_Empty_Msg"] = ("Introduzca una clave válida de OpenRouter antes de guardar.", "Enter a valid OpenRouter key before saving."),
            ["AiConfig_OpenRouter_Empty_Title"] = ("API Key vacía", "Empty API Key"),
            ["AiConfig_OpenRouter_Saved_Msg"] = ("Clave de OpenRouter guardada correctamente y cifrada mediante Windows DPAPI.", "OpenRouter key saved successfully and encrypted using Windows DPAPI."),
            ["AiConfig_OpenRouter_Saved_Title"] = ("Seguridad DictaMeeting", "DictaMeeting Security"),
            ["AiConfig_OpenRouter_Delete_Confirm"] = ("¿Está seguro de que desea eliminar la clave de API guardada de OpenRouter?", "Are you sure you want to delete the saved OpenRouter API key?"),
            ["AiConfig_Custom_Endpoint_Empty_Msg"] = ("Introduzca una URL de Endpoint válida para el Servidor personalizado (ej. https://mi-servidor.com/v1).", "Enter a valid Endpoint URL for the Custom server (e.g. https://my-server.com/v1)."),
            ["AiConfig_Custom_Endpoint_Empty_Title"] = ("Endpoint requerido", "Endpoint required"),
            ["AiConfig_Custom_Model_Empty_Msg"] = ("Introduzca el nombre del modelo para el Servidor personalizado (ej. qwen3.8-27b).", "Enter the model name for the Custom server (e.g. qwen3.8-27b)."),
            ["AiConfig_Custom_Model_Empty_Title"] = ("Modelo requerido", "Model required"),
            ["AiConfig_Custom_Saved_Msg"] = ("Configuración del Servidor personalizado guardada correctamente.", "Custom server configuration saved successfully."),
            ["AiConfig_Custom_Saved_Title"] = ("Servidor personalizado", "Custom Server"),
            ["AiConfig_Custom_Delete_Confirm"] = ("¿Está seguro de que desea eliminar la clave de API del Servidor personalizado?", "Are you sure you want to delete the Custom server API key?"),
            ["AiConfig_Confirm_Delete_Title"] = ("Confirmar eliminación", "Confirm deletion"),

            // Vocabulary Modal
            ["Vocab_Title"] = ("Vocabulario y palabras clave", "Vocabulary & Keywords"),
            ["Vocab_Subtitle"] = ("Mejora el reconocimiento de nombres, acrónimos y términos específicos.", "Improve recognition of names, acronyms and specific terms."),
            ["Vocab_Section_Add"] = ("AÑADIR O ACTUALIZAR TÉRMINO", "ADD OR UPDATE TERM"),
            ["Vocab_Field_Word"] = ("Palabra o Acrónimo oficial:", "Official Word or Acronym:"),
            ["Vocab_Field_Word_Tooltip"] = ("Escriba la palabra canónica (ej. Aritz) y pulse Enter para guardar", "Enter canonical word (e.g. Aritz) and press Enter to save"),
            ["Vocab_Field_Variants"] = ("Variantes / Fonética (sugerida automáticamente):", "Variants / Phonetics (automatically suggested):"),
            ["Vocab_Field_Variants_Tooltip"] = ("Variantes separadas por comas. Se autocompletan solas y son editables. Pulse Enter para guardar.", "Variants separated by commas. Automatically suggested and editable. Press Enter to save."),
            ["Vocab_Tip_Auto"] = ("Las variantes fonéticas se sugieren solas para euskera, castellano y acrónimos.", "Phonetic variants are automatically suggested for Basque, Spanish and acronyms."),
            ["Vocab_Search_Placeholder"] = ("Buscar en el glosario por palabra o variante...", "Search glossary by word or variant..."),
            ["Vocab_Import_Json"] = ("Importar JSON", "Import JSON"),
            ["Vocab_Import_Tooltip"] = ("Cargar vocabulario desde un archivo JSON externo", "Load vocabulary from an external JSON file"),
            ["Vocab_Export_Json"] = ("Exportar JSON", "Export JSON"),
            ["Vocab_Export_Tooltip"] = ("Exportar la lista completa de términos a un archivo JSON para compartirlo", "Export full list of terms to a JSON file to share"),
            ["Vocab_Save_Button"] = ("Guardar", "Save"),
            ["Vocab_Edit_Tooltip"] = ("Editar este término en el formulario", "Edit this term in the form"),
            ["Vocab_Delete_Tooltip"] = ("Eliminar este término", "Delete this term"),
            ["Vocab_Variants_Prefix"] = ("Variantes: ", "Variants: "),
            ["Vocab_Count_Format"] = ("{0} términos registrados", "{0} registered terms"),
            ["Vocab_Msg_EnterWord"] = ("Por favor, introduzca una palabra o acrónimo.", "Please enter a word or acronym."),
            ["Vocab_Msg_Saved"] = ("'{0}' guardado con éxito.", "'{0}' saved successfully."),
            ["Vocab_Msg_Removed"] = ("'{0}' eliminado.", "'{0}' removed."),
            ["Vocab_Msg_ExportSuccess"] = ("Vocabulario exportado con éxito a '{0}'.", "Vocabulary successfully exported to '{0}'."),
            ["Vocab_Msg_ExportError"] = ("Error al exportar: {0}", "Error exporting: {0}"),
            ["Vocab_Msg_ImportSuccess"] = ("Vocabulario importado con éxito desde '{0}'.", "Vocabulary successfully imported from '{0}'."),
            ["Vocab_Msg_ImportError"] = ("Error al importar: {0}", "Error importing: {0}"),
            ["Vocab_Dialog_ExportTitle"] = ("Exportar Vocabulario DictaMeeting", "Export DictaMeeting Vocabulary"),
            ["Vocab_Dialog_ImportTitle"] = ("Importar Vocabulario a DictaMeeting", "Import Vocabulary to DictaMeeting"),

            // Privacy & Data Modal
            ["Privacy_Title"] = ("Privacidad y grabación", "Privacy & Recording"),
            ["Privacy_Section_Storage"] = ("Procesamiento y Almacenamiento de Datos", "Data Processing & Storage"),
            ["Privacy_Storage_Audio"] = ("El audio de las reuniones se procesa y almacena localmente en este equipo.", "Meeting audio is processed and stored locally on this computer."),
            ["Privacy_Storage_Transcript"] = ("La transcripción y la diarización se realizan localmente.", "Transcription and diarization are performed locally."),
            ["Privacy_Storage_Diarization"] = ("La separación e identificación de interlocutores se realiza localmente.", "Speaker separation and identification is performed locally."),
            ["Privacy_Storage_Ai"] = ("El contenido necesario se envía al proveedor seleccionado para generar el acta.", "Necessary content is sent to the selected provider to generate minutes."),
            ["Privacy_Storage_Local_Badge"] = ("✓ Local", "✓ Local"),
            ["Privacy_Storage_Provider_Badge"] = ("⚠ Según proveedor", "⚠ Depends on provider"),
            ["Privacy_Storage_AiProvider_Label"] = ("Proveedor de IA para actas: ", "AI provider for minutes: "),
            ["Privacy_Notice_Toggle"] = ("Mostrar recordatorio antes de iniciar una grabación", "Show reminder before starting a recording"),
            ["Privacy_Disclaimer"] = ("DictaMeeting es una herramienta de grabación y procesamiento de reuniones. El usuario es responsable de utilizarla de acuerdo con la normativa y las políticas aplicables a su organización.", "DictaMeeting is a meeting recording and processing tool. The user is responsible for using it in accordance with applicable regulations and organizational policies."),
            ["Privacy_Item_Recording"] = ("Grabación", "Recording"),
            ["Privacy_Item_Transcript"] = ("Transcripción", "Transcription"),
            ["Privacy_Item_Diarization"] = ("Diarización", "Diarization"),
            ["Privacy_Item_Minutes"] = ("Generación del acta", "Minutes generation"),

            // About Modal
            ["About_Title"] = ("Acerca de DictaMeeting", "About DictaMeeting"),
            ["About_Subtitle"] = ("DictaMeeting • Transcripción local y privada • Creado por Aritz Villodas", "DictaMeeting • Local & private transcription • Created by Aritz Villodas"),
            ["About_Description"] = ("DictaMeeting está diseñado para mantener el procesamiento de audio y transcripción en el equipo siempre que sea posible, permitiendo conectar opcionalmente servicios de IA externos para la generación de actas.", "DictaMeeting is designed to keep audio processing and transcription on your machine whenever possible, with optional external AI services for minutes generation."),
            ["About_Created_By"] = ("Creado por", "Created by"),
            ["About_Project"] = ("Proyecto", "Project"),
            ["About_Tech_Title"] = ("Tecnologías", "Technologies"),
            ["About_Tech_License_Notice"] = ("DictaMeeting utiliza software y modelos open source de distintos proyectos y comunidades.", "DictaMeeting uses open-source software and models from various projects and communities."),
            ["About_GitHub_Tooltip"] = ("Abrir repositorio en GitHub en el navegador", "Open GitHub repository in browser"),
            ["About_Tech_App"] = ("Aplicación de escritorio", "Desktop application"),
            ["About_Tech_UI"] = ("Interfaz de usuario", "User interface"),
            ["About_Tech_Inference"] = ("Inferencia local", "Local inference"),
            ["About_Tech_Speech"] = ("Reconocimiento de voz", "Speech recognition"),
            ["About_Tech_Qwen"] = ("Transcripción multilingüe avanzada", "Advanced multilingual transcription"),
            ["About_Tech_VAD"] = ("Detección de actividad por voz", "Voice activity detection"),
            ["About_Tech_Diarization"] = ("Diarización y separación de interlocutores", "Speaker diarization and separation"),
            ["About_Tech_AudioCapture"] = ("Captura de audio WASAPI", "WASAPI audio capture"),

            // Acta Modal
            ["Acta_Modal_Title"] = ("Acta Ejecutiva de la Reunión", "Executive Meeting Minutes"),
            ["Acta_Check_Participants"] = ("Participantes", "Participants"),
            ["Acta_Check_Decisions"] = ("Decisiones", "Decisions"),
            ["Acta_Check_Actions"] = ("Acciones", "Actions"),
            ["Acta_Check_Pending"] = ("Pendientes", "Pending"),
            ["Acta_Check_Impersonal"] = ("Acta impersonal", "Impersonal minutes"),
            ["Acta_Button_Generate"] = ("⚡ Generar Acta con IA", "⚡ Generate Minutes with AI"),
            ["Acta_Button_Copy"] = ("📋 Copiar al Portapapeles", "📋 Copy to Clipboard"),
            ["Acta_Button_SaveMd"] = ("💾 Guardar Acta (.md)", "💾 Save Minutes (.md)"),
            ["Acta_Button_Folder"] = ("📁 Carpeta Reunión", "📁 Meeting Folder"),
            ["Acta_Level_Detail"] = ("Nivel de Detalle", "Detail Level"),
            ["Acta_Language_Label"] = ("Idioma", "Language"),
            ["Acta_Detail_Breve"] = ("Breve", "Brief"),
            ["Acta_Detail_Normal"] = ("Normal", "Normal"),
            ["Acta_Detail_Detallada"] = ("Detallada", "Detailed"),
            ["Acta_Detail_Exhaustiva"] = ("Exhaustiva", "Comprehensive"),

            // Pre-recording Reminder
            ["Notice_Title"] = ("Antes de comenzar", "Before you begin"),
            ["Notice_Reminder"] = ("Recuerda informar a los participantes antes de comenzar a grabar.", "Remember to inform participants before starting to record."),
            ["Notice_Text"] = ("Asegúrate de que los participantes han sido informados de que esta reunión será grabada y de que el uso de la grabación es adecuado a la normativa y políticas aplicables.", "Make sure participants have been informed that this meeting will be recorded and that the recording complies with applicable laws and policies."),
            ["Notice_DontShowAgain"] = ("No volver a mostrar este aviso", "Do not show this reminder again"),
            ["Notice_Continue"] = ("Continuar a DictaMeeting", "Continue to DictaMeeting"),
            ["Notice_Start"] = ("Comenzar", "Start"),
            ["Notice_Cancel"] = ("Cancelar", "Cancel"),

            // First-run Onboarding Modal
            ["Onboarding_Title"] = ("Modelos básicos", "Basic Models"),
            ["Onboarding_Subtitle"] = ("Descarga los modelos recomendados para empezar a usar DictaMeeting.", "Download recommended models to start using DictaMeeting."),
            ["Onboarding_Download_Button"] = ("Descargar Modelo Recomendado", "Download Recommended Model"),
            ["Onboarding_Skip_Button"] = ("Ahora no", "Not now"),
            ["Onboarding_Skip_Tooltip"] = ("Cerrar el asistente. Los modelos podrán descargarse más tarde desde Ajustes.", "Close the assistant. Models can be downloaded later from Settings."),
            ["Onboarding_ViewAll_Button"] = ("Ver Todos los Modelos", "View All Models"),
            ["Onboarding_Location_Label"] = ("Ubicación:", "Location:"),
            ["Onboarding_Available_Badge"] = ("✓ Disponible", "✓ Available"),
            ["Onboarding_Pending_Badge"] = ("↓ Pendiente", "↓ Pending"),
            ["Onboarding_Attention_Title"] = ("⚠️ Atención", "⚠️ Attention"),
            ["Onboarding_Retry_Button"] = ("Reintentar descarga", "Retry download"),
            ["Onboarding_Continue_Button"] = ("Continuar a DictaMeeting", "Continue to DictaMeeting"),
            ["Onboarding_Download_One"] = ("Descargar 1 modelo", "Download 1 model"),
            ["Onboarding_Download_Many"] = ("Descargar {0} modelos", "Download {0} models"),
            ["Onboarding_Download_Default"] = ("Descargar modelos", "Download models"),
            ["Role_Live_Summary"] = ("Resumen en vivo", "Live summary"),
            ["Role_Live_Transcription"] = ("Transcripción en vivo", "Live transcription"),
            ["Role_Final_Transcription"] = ("Transcripción final", "Final transcript"),
            ["Hardware_Summary_Format"] = ("CPU con {0} núcleos y {1:F0} GB de RAM. Recomendado en vivo: {2} | Final: {3}.", "CPU with {0} cores and {1:F0} GB RAM. Recommended live: {2} | Final: {3}."),

            // Audio & Transcript Import Modals
            ["Import_Audio_Title"] = ("Importar Archivo de Audio", "Import Audio File"),
            ["Import_Audio_Desc"] = ("Carga un archivo de audio para crear una nueva reunión y procesar la transcripción y separación de interlocutores en segundo plano.", "Load an audio file to create a new meeting and process transcription and speaker diarization in the background."),
            ["Import_Audio_Drop"] = ("Arrastra y suelta tu archivo de audio aquí", "Drag and drop your audio file here"),
            ["Import_Audio_OrBrowse"] = ("o haz clic en cualquier lugar para examinar archivos", "or click anywhere to browse files"),
            ["Import_Audio_Formats"] = ("Formatos admitidos: WAV, MP3, M4A, FLAC, OGG, WMA, AAC", "Supported formats: WAV, MP3, M4A, FLAC, OGG, WMA, AAC"),
            ["Import_Audio_Supported"] = ("Formatos admitidos:", "Supported formats:"),
            ["Import_Audio_Button"] = ("Importar y Procesar", "Import & Process"),
            ["Import_Audio_Change"] = ("Cambiar", "Change"),
            ["Import_Audio_Note"] = ("⚙️ Se procesará con el modelo final configurado y los ajustes actuales de idioma.", "⚙️ Will be processed with the configured final model and current language settings."),
            ["Import_Transcript_Title"] = ("Importar Transcripción", "Import Transcript"),
            ["Import_Transcript_Desc"] = ("Carga un archivo de texto con la transcripción de una reunión. La reunión se creará directamente en el historial sin procesar audio.", "Load a text file with a meeting transcript. The meeting will be created directly in history without audio processing."),
            ["Import_Transcript_Drop"] = ("Arrastra y suelta tu archivo de transcripción aquí", "Drag and drop your transcript file here"),
            ["Import_Transcript_Notice"] = ("La transcripción se importará tal cual. Si contiene speakers y timestamps, se conservarán. No se ejecutará Whisper ni diarización.", "The transcript will be imported as-is. If it contains speakers and timestamps, they will be preserved. Whisper and diarization will not be run."),
            ["Import_Transcript_Button"] = ("Importar Transcripción", "Import Transcript"),
            ["Import_Transcript_Change"] = ("Cambiar", "Change"),

            // Common
            ["Common_Accept"] = ("Aceptar", "OK"),
            ["Common_Cancel"] = ("Cancelar", "Cancel"),
            ["Common_Close"] = ("Cerrar", "Close"),
            ["Common_Save"] = ("Guardar", "Save"),
            ["Common_Delete"] = ("Eliminar", "Delete"),
            ["Common_Copy"] = ("Copiar", "Copy"),
            ["Common_Copied"] = ("Copiado", "Copied"),
            ["Common_Download"] = ("Descargar", "Download"),
            ["Common_Refresh"] = ("Actualizar", "Refresh"),
            ["Common_Browse"] = ("Examinar archivo...", "Browse file..."),
            ["Common_Error"] = ("Error", "Error"),
            ["Common_Warning"] = ("Aviso", "Warning"),
            ["Common_Success"] = ("Éxito", "Success"),
            ["Common_Information"] = ("Información", "Information"),
            ["Common_Understood"] = ("Entendido", "Understood"),
            ["Common_Folder"] = ("Carpeta Reunión", "Meeting Folder"),
            ["Common_OpenFolder"] = ("Abrir Carpeta", "Open Folder"),
            ["Common_Export"] = ("Exportar", "Export"),
            ["Common_Updating"] = ("⚡ Actualizando...", "⚡ Updating..."),
            ["Common_Model_Prefix"] = ("Modelo: ", "Model: "),
            ["Common_Workspace_Meeting"] = ("Workspace de Reunión", "Meeting Workspace"),
            ["Common_Auto_Recommended"] = ("Automático (Recomendado por Hardware)", "Automatic (Hardware Recommended)"),
            ["Common_Folder_NotFound_Title"] = ("Carpeta no encontrada", "Folder not found"),
            ["Common_Folder_NotFound_Msg"] = ("La carpeta de reuniones aún no existe:\n{0}", "Meeting folder does not exist yet:\n{0}"),
            ["Common_Clipboard_Error"] = ("No se pudo copiar al portapapeles: {0}", "Could not copy to clipboard: {0}"),
            ["Common_Audio_Device_Warning"] = ("Aviso de Dispositivo de Audio", "Audio Device Notice"),
            ["Common_Active_Recording_Title"] = ("Grabación en curso", "Recording in progress"),
            ["Common_Active_Recording_Msg"] = ("Hay una reunión en grabación activa. ¿Desea detenerla antes de abrir esta reunión?", "A meeting is actively recording. Do you want to stop it before opening this meeting?"),
            ["Common_Participants_Count"] = ("{0} participantes", "{0} participants"),
            ["Common_Terms_Count"] = ("{0} términos", "{0} terms"),

            // Nuevas claves para tooltips y diálogos MessageBox
            ["Common_Change"] = ("Cambiar", "Change"),
            ["Vocab_Save_Tooltip"] = ("Guardar término y sus variantes fonéticas", "Save term and its phonetic variants"),
            ["Msg_Meeting_Active_Title"] = ("Reunión en Curso", "Meeting in Progress"),
            ["Msg_Meeting_Active_NewSession"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de iniciar una nueva sesión.", "A meeting is actively recording or initializing. You must wait or stop it before starting a new session."),
            ["Msg_Meeting_Active_ImportAudio"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de importar audio.", "A meeting is actively recording or initializing. You must wait or stop it before importing audio."),
            ["Msg_Meeting_Active_ImportTranscript"] = ("Hay una reunión en grabación activa o inicializándose. Debe esperar o detenerla antes de importar una transcripción.", "A meeting is actively recording or initializing. You must wait or stop it before importing a transcript."),
            ["Msg_Import_Audio_Error_Title"] = ("Error de Importación", "Import Error"),
            ["Msg_Import_Audio_Error"] = ("Error al importar el archivo de audio: {0}", "Error importing audio file: {0}"),
            ["Msg_Import_Transcript_Invalid_Title"] = ("Archivo no válido", "Invalid File"),
            ["Msg_Import_Transcript_Error"] = ("Error al importar la transcripción: {0}", "Error importing transcript: {0}"),
            ["Msg_Meeting_Start_Error_Title"] = ("Error al Iniciar", "Startup Error"),
            ["Msg_Meeting_Start_Error"] = ("Ocurrió un error al iniciar la reunión: {0}", "An error occurred while starting the meeting: {0}"),
            ["Msg_Meeting_Reprocess_NoAudio_Title"] = ("Audio no disponible", "Audio Not Available"),
            ["Msg_Meeting_Reprocess_NoAudio"] = ("No se encontró el archivo de audio guardado en disco para esta reunión. No es posible reprocesar.", "The audio file saved on disk for this meeting was not found. Cannot reprocess."),
            ["Msg_Meeting_Folder_NotExists"] = ("La carpeta de la reunión aún no existe:\n{0}", "Meeting folder does not exist yet:\n{0}"),
            ["Msg_OpenRouter_Empty_Title"] = ("API Key vacía", "Empty API Key"),
            ["Msg_OpenRouter_Empty"] = ("Introduzca una clave válida de OpenRouter antes de guardar.", "Enter a valid OpenRouter key before saving."),
            ["Msg_OpenRouter_Saved_Title"] = ("Seguridad DictaMeeting", "DictaMeeting Security"),
            ["Msg_OpenRouter_Saved"] = ("Clave de OpenRouter guardada correctamente y cifrada mediante Windows DPAPI.", "OpenRouter key saved successfully and encrypted using Windows DPAPI."),
            ["Msg_OpenRouter_Delete_Confirm_Title"] = ("¿Eliminar clave?", "Delete Key?"),
            ["Msg_OpenRouter_Delete_Confirm"] = ("¿Desea eliminar la clave guardada de OpenRouter?", "Do you want to delete the saved OpenRouter key?"),
            ["Msg_CustomServer_Endpoint_Required_Title"] = ("Endpoint requerido", "Endpoint Required"),
            ["Msg_CustomServer_Endpoint_Required"] = ("Introduzca una URL de Endpoint válida para el Servidor personalizado (ej. https://mi-servidor.com/v1).", "Enter a valid Endpoint URL for Custom Server (e.g. https://my-server.com/v1)."),
            ["Msg_CustomServer_Model_Required_Title"] = ("Modelo requerido", "Model Required"),
            ["Msg_CustomServer_Model_Required"] = ("Introduzca el nombre del modelo para el Servidor personalizado (ej. qwen3.8-27b).", "Enter the model name for Custom Server (e.g. qwen3.8-27b)."),
            ["Msg_CustomServer_Saved_Title"] = ("Servidor personalizado", "Custom Server"),
            ["Msg_CustomServer_Saved"] = ("Configuración del Servidor personalizado guardada correctamente.", "Custom server configuration saved successfully."),
            ["Msg_CustomServer_Delete_Confirm_Title"] = ("¿Eliminar clave?", "Delete Key?"),
            ["Msg_CustomServer_Delete_Confirm"] = ("¿Desea eliminar la clave guardada del Servidor personalizado?", "Do you want to delete the saved Custom Server key?"),
            ["Msg_Model_Location_Unavailable_Title"] = ("Ubicación No Disponible", "Location Not Available"),
            ["Msg_Model_Location_Unavailable"] = ("La ubicación configurada ({0}) no está disponible. Conecte la unidad o seleccione otra ubicación antes de descargar.", "The configured location ({0}) is not available. Connect the drive or select another location before downloading."),
            ["Msg_Model_Downloaded_Ready_Title"] = ("DictaMeeting — Modelo Listo", "DictaMeeting — Model Ready"),
            ["Msg_Model_Downloaded_Ready"] = ("El modelo {0} se ha descargado correctamente y está listo para transcribir.", "Model {0} was downloaded successfully and is ready to transcribe."),
            ["Msg_Model_Download_Error_Title"] = ("Error de Descarga", "Download Error"),
            ["Msg_Model_Download_Error"] = ("Error al descargar el modelo {0}: {1}", "Error downloading model {0}: {1}"),
            ["Msg_Model_Delete_Confirm_Title"] = ("Eliminar Modelo Local", "Delete Local Model"),
            ["Msg_Model_Delete_Confirm"] = ("¿Está seguro de que desea eliminar el archivo local del modelo '{0}' ({1}) para liberar espacio en disco?", "Are you sure you want to delete the local file for model '{0}' ({1}) to free up disk space?"),
            ["Msg_Model_Folder_Invalid_Title"] = ("Ubicación No Válida", "Invalid Location"),
            ["Msg_Model_Folder_Invalid_Default"] = ("La carpeta seleccionada no es válida.", "The selected folder is not valid."),
            ["Msg_Model_Folder_Configured_Title"] = ("Ubicación de Modelos", "Models Location"),
            ["Msg_Model_Folder_Configured"] = ("La ubicación de los modelos se ha configurado en:\n{0}", "Models location has been configured in:\n{0}"),
            ["Msg_Model_Change_Error_Title"] = ("Error", "Error"),
            ["Msg_Model_Change_Error"] = ("Error al cambiar la ubicación:\n{0}", "Error changing location:\n{0}"),
            ["Msg_Model_Change_Without_Move_Title"] = ("Cambiar sin mover", "Change Without Moving"),
            ["Msg_Model_Change_Without_Move"] = ("Los modelos existentes permanecerán en la ubicación anterior y no se copiarán a la nueva carpeta.\n\n¿Desea cambiar la ubicación de todos modos?", "Existing models will remain in the previous location and will not be copied to the new folder.\n\nDo you want to change location anyway?"),
            ["Msg_Model_Migrate_Success_Title"] = ("Migración Completada", "Migration Completed"),
            ["Msg_Model_Migrate_Success"] = ("Todos los modelos han sido migrados con éxito y verificados en la nueva ubicación:\n{0}", "All models have been migrated successfully and verified in the new location:\n{0}"),
            ["Msg_Model_Migrate_Cancelled_Title"] = ("Migración Cancelada", "Migration Cancelled"),
            ["Msg_Model_Migrate_Cancelled"] = ("La migración ha sido cancelada. Los modelos originales permanecen intactos en la ubicación anterior y no se ha modificado la configuración.", "Migration was cancelled. Original models remain intact in the previous location and settings have not been modified."),
            ["Msg_Audio_Device_Notice_Title"] = ("Aviso de Dispositivo de Audio", "Audio Device Notice")
        };

        // Encontrar ruta raíz
        var current = AppContext.BaseDirectory;
        while (!string.IsNullOrEmpty(current) && !File.Exists(Path.Combine(current, "DictaMeeting.sln")))
        {
            current = Path.GetDirectoryName(current);
        }

        Assert.NotNull(current);
        var resDir = Path.Combine(current, "src", "DictaMeeting.App", "Resources");
        Directory.CreateDirectory(resDir);

        void WriteResx(string filePath, Func<(string es, string en), string> selector)
        {
            var root = new XElement("root",
                new XElement("resheader", new XAttribute("name", "resmimetype"), new XElement("value", "text/microsoft-resx")),
                new XElement("resheader", new XAttribute("name", "version"), new XElement("value", "2.0")),
                new XElement("resheader", new XAttribute("name", "reader"), new XElement("value", "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")),
                new XElement("resheader", new XAttribute("name", "writer"), new XElement("value", "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"))
            );

            foreach (var kvp in dict)
            {
                var val = selector(kvp.Value);
                root.Add(new XElement("data",
                    new XAttribute("name", kvp.Key),
                    new XAttribute(XNamespace.Xml + "space", "preserve"),
                    new XElement("value", val)
                ));
            }

            var doc = new XDocument(new XDeclaration("1.0", "utf-8", "yes"), root);
            doc.Save(filePath);
        }

        WriteResx(Path.Combine(resDir, "Strings.resx"), x => x.es);
        WriteResx(Path.Combine(resDir, "Strings.es.resx"), x => x.es);
        WriteResx(Path.Combine(resDir, "Strings.en.resx"), x => x.en);
    }
}
